config/routes.rb
Rails.application.routes.draw do

  root :to => "front#index"
  get 'dashboard' => 'dashboard#index'

  get     "login"    => "session#new"
  post    "login"    => "session#create"
  delete  "logout"   => "session#destroy"
  get  "" => "session#new"
  resources:users
  resources:roles
  resources:fronts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, length: { maximum: 20 }, presence: true
  validates :email, presence:true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
  include SessionHelper

  before_action :require_login
  def require_login
    unless require_login?
      redirect_to login_path
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    render layout: "backend"
  end
end

app/controllers/fronts_controller.rb
class FrontsController < ApplicationController
  def index
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def index
    @role = Role.all
    render layout: "backend"
  end

  def new
  end

  def create
  end

  def edit
  end

  def show
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  def new
  end

  def create
    # data = JSON.parse(request.body.read)
    user = User.find_by email: params[:session][:email].downcase
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Login success"
      log_in user
      redirect_to users_path
    else
      flash[:danger] = "Invalid email/password combination"
      render :new
    end
  end
  def destroy
    log_out
    flash[:success] = "You are logged out"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @stt = 0;
    @users = User.all
    render layout: "backend"
  end
  def new
    @user = User.new
    render layout: "backend"
  end
  def create
     @user = User.new user_params
     if@user.save
       flash[:success]="Register success (^.^)"
       redirect_to users_path
     else
       flash[:danger]="Register fails!!"
       render :new
     end
  end
  def edit
    @user = User.find(params[:id])
    render layout: "backend"
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success]="Update User Success"
      redirect_to users_path
    else
      flash[:danger]="Update Fails!!"
      render :new
    end

  end
  def show
      @users= User.find_by id: params[:id]
      render layout: "backend"
  end
  def destroy
     User.find(params[:id]).destroy
     flash[:success] = "You delete success"
     redirect_to users_url
  end

  private
  def user_params
     params.require(:user).permit :name, :email, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/fronts_helper.rb
module FrontsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/session_helper.rb
module SessionHelper
  #login
  def log_in user
    session[:user_id] = user.id
  end
  #logout
  def log_out
    session.delete :user_id
  end
  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end
  #check user has logged in before
  def require_login?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Dashboard</li>
  </ol>
</section>
<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-lg-3 col-xs-6">
      <!-- small box -->
      <div class="small-box bg-aqua">
        <div class="inner">
          <h3>&nbsp;</h3>

          <p>Accounts</p>
        </div>
        <div class="icon">
          <i class="fa fa-file-text-o" aria-hidden="true"></i>
        </div>
        <a href="/users" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
      <!-- small box -->
      <div class="small-box bg-green">
        <div class="inner">
          <h3>&nbsp;</h3>


          <p>Roles</p>
        </div>
        <div class="icon">
          <i class="fa fa-television" aria-hidden="true"></i>
        </div>
        <a href="/roles" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
      </div>
    </div>
  </div>
</section>

app/views/fronts/index.html.erb
<h1>Home My app</h1>
<p>Find me in app/views/fronts/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <section class="content" style="min-height: auto; text-align: center; font-weight: bold;">
      <% flash.each do |key, value| %>
        <div class="row">
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        </div>
      <% end %>
    </section>
  </body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Training</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'backend', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'backend', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  </head>

  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <header class="main-header">
        <!-- Logo -->
        <a href="/dashboard" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>RAILS</b></span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg">RAILS</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>

          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
               <!--Messages: style can be found in dropdown.less-->
              <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <span class="hidden-xs">
                  <%= render "users/showAdmin" %>
                </span>
              </a>
              <ul class="dropdown-menu">
                <!-- User image -->
                <li class="user-header">
                     <%= image_tag "img/avatar5.png", class: "img-circle", alt: "User Image"  %>
                  <p>
                    Admin Managers
                    <small><%= Date.current %></small>
                  </p>
                </li>
                <!-- Menu Body -->
                <li class="user-body">
                  <div class="row">
                    <div class="col-xs-4 text-center">
                      <a href="#">Followers</a>
                    </div>
                    <div class="col-xs-4 text-center">
                      <a href="#">Sales</a>
                    </div>
                    <div class="col-xs-4 text-center">
                      <a href="#">Friends</a>
                    </div>
                  </div>
                  <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">

                </div>
                <div class="pull-right">
                  <button class="btn btn-default btn-flat"><%= link_to "Logout", logout_path, method: :delete%></button>
                </div>
              </li>
            </ul>
          </li>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
<!--             <div class="pull-left image">

            </div>
            <div class="pull-left info">

              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div> -->
          </div>
          <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>

            <li id="dashboard" class="">
              <a href="/dashboard">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                <span class="pull-right-container">
                <!--<i class="fa fa-angle-left pull-right"></i>-->
              </span>
              </a>
              <!--<ul class="treeview-menu">
                <li class="active"><a href="index.html"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
                <li><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
              </ul>-->
            </li>

            <li id="order" class=""><a href="/order/list"><i class="fa fa-file-text-o" aria-hidden="true"></i> <span>Order</span></a></li>
            <li id="product" class=""><a href="/product/list"><i class="fa fa-television" aria-hidden="true"></i> <span>Product</span></a></li>
            <!--<li class="header">LABELS</li>-->
            <li class="treeview">
                <a href="#">
                  <i class="fa fa-user-o" aria-hidden="true"></i><span>Account</span>
                  <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                  </span>
                </a>
                <ul class="treeview-menu" style="display: none;">
                  <li><a href="/users"><i class="fa fa-circle-o"></i>Accounts</a></li>
                  <li><a href="/roles"><i class="fa fa-circle-o"></i>Roles</a></li>
                </ul>
            </li>
            </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper" style="min-height: 577px;">

        <%= yield %>

      </div>
      <!-- /.content-wrapper -->
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <!--<b>Version</b> 2.4.0-->
        </div>
        <strong>Copyright &copy; 2018 <a href="#">Hoangpv</a>.</strong> All rights
        reserved.
      </footer>

      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
  <script type="text/javascript">
    $(document).ready(function() {
    $('#example1').DataTable();
  });
  </script>
  </body>
</html>

app/views/roles/create.html.erb
<h1>Roles#create</h1>
<p>Find me in app/views/roles/create.html.erb</p>

app/views/roles/edit.html.erb
<h1>Roles#edit</h1>
<p>Find me in app/views/roles/edit.html.erb</p>

app/views/roles/index.html.erb
<h1>Roles#index</h1>
<p>Find me in app/views/roles/index.html.erb</p>

app/views/roles/new.html.erb
<h1>Roles#new</h1>
<p>Find me in app/views/roles/new.html.erb</p>

app/views/roles/show.html.erb
<h1>Roles#show</h1>
<p>Find me in app/views/roles/show.html.erb</p>

app/views/session/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="title">Login</h1>
  </div>
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <%= form_for :session, url: login_path do |f| %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email,type: "email", placeholder: "Enter your email", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, placeholder: "Enter your password",
            class: "form-control" %>
        </div>
        <div class="text-center">
          <%= f.submit "Login", class: "btn btn-info col-lg-12" %>
        </div>
        <div class="text-right">
          <%= link_to "Forgot Password?", new_user_path %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_profileAdmin.hmtl.erb
<h5><%= current_user.name %></h5>

app/views/users/_profileAmind.html.erb
<h4><%= current_user.name %></h4>
<h4><%= current_user.name %></h4>

app/views/users/_showAdmin.html.erb
<h5><%= current_user.name %></h5>

app/views/users/_showadmin.html.erb
<h4><%= current_user.name %></h4>

app/views/users/edit.html.erb
<div class="box-body">
  <div class="box-header">
    <h3 class="box-title">Create new users</h3>
  </div>
  <div class="row">
    <div class="col-lg-offset-2">
      <%= form_for @user, html: {class: "form-horizontal"} do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name", class: "col-md-2 control-label" %>
          <div class="col-md-5">
            <%= f.text_field :name, class: "form-control", placeholder: "Enter user name" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :email, "Email", class: "col-md-2 control-label" %>
          <div class="col-md-5">
            <%= f.text_field :email, type: "email", class: "form-control", placeholder: "Enter user Email" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password, "Password", class: "col-md-2 control-label" %>
          <div class="col-md-5">
            <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, "Password Confirmation", class: "col-md-2 control-label" %>
          <div class="col-md-5">
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password confirmation" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-offset-6">
            <%= f.submit "Register", class: "btn btn-success" %>
          </div>
          <div class="col-lg-offset-1">
            <%= link_to "Back", user_path, class: "btn btn-secondary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="box">
        <div class="box-header">
          <h3 class="box-title">Data Table With Users</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
            <div class="row">
              <div class="col-md-12">
                <button type="button" class="btn btn-info"><%= link_to "Create", new_user_path %></button>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
               <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                <thead>
                <tr role="row">
                  <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="width: 275px;">STT
                  </th>
                  <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 345px;">Name</th>
                  <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 317px;">Email</th>
                  <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending" style="width: 180px;">updated_at</th>
                  <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending" style="width: 180px;">created_at</th>
                  <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending" style="width: 180px;">option_at</th>
                </tr>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                    <tr role="row" class="odd">
                      <td class="sorting_1"><%= @stt+=1 %></td>
                      <td><%= user.name %></td>
                      <td><%= user.email %></td>
                      <td><%= user.created_at %></td>
                      <td><%= user.updated_at %></td>
                      <td><button type="button" class="btn btn-info"><%= link_to "show", user %></button>
                          <button type="button" class="btn btn-warning"><%= link_to "Edit", edit_user_path(user) %>
                          </button>
                          <button type="button" class="btn btn-danger"><%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
                          </button>
                      </td>
                    </tr>
                    <% end %>
               </tbody>
              </table></div></div>
            </div>
          </div>
                <!-- /.box-body -->
  </div>

app/views/users/new.html.erb
<div class="box-body">
  <div class="box-header">
    <h3 class="box-title">Create new users</h3>
  </div>
  <div class="row">
    <div class="col-lg-offset-2">
      <%= form_for @user, html: {class: "form-horizontal"} do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name", class: "col-md-2 control-label" %>
          <div class="col-md-5">
            <%= f.text_field :name, class: "form-control", placeholder: "Enter user name" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :email, "Email", class: "col-md-2 control-label" %>
          <div class="col-md-5">
            <%= f.text_field :email, type: "email", class: "form-control", placeholder: "Enter user Email" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password, "Password", class: "col-md-2 control-label" %>
          <div class="col-md-5">
            <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, "Password Confirmation", class: "col-md-2 control-label" %>
          <div class="col-md-5">
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password confirmation" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-offset-6">
            <%= f.submit "Register", class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <div class="text-left">
        <label><%= @users.name %></label>
      </div>
      <%= link_to "Logout", logout_path, method: :delete %>
    </div>
  </div>
</div>